Allow gromacs mdp file writer to use the new free_energy_mixin
Exscientia/BioSimSpace pull request #3
Opened 2022-05-17 17:00 UTC by xiki-tempula

Allow config to write multiple stage lambda into Gromacs mdp files
Change the default mdp options to better suit the gmx-2022
Add setLambda method to BSS.protocol.free_energy_mixin
Change the maxwarn to use the Gromacs unlimited option
FIx the issue of the existing gromacs tests
FIx the issue that the BSS.FreeEnergy.relative cannot use the new lambda config
Write test to ensure that the mdp file has been modified
Change the folder being created to use the index of the lambda (e.g. lambda_0, lambda_1 ... lambda_32)

2022-05-18 08:10 UTC, msuruzhon commented on python/BioSimSpace/Sandpit/Exscientia/Protocol/_config.py
> +            protocol_dict["integrator"] = "md"                                      # Langevin dynamics.
Change the comment

2022-05-18 08:12 UTC, msuruzhon commented on python/BioSimSpace/Sandpit/Exscientia/Protocol/_config.py
> +            protocol_dict["nstdhdl"] = 1000                                         # Write gradients every 200 steps.
Should we keep the energy output consistent between the MD engines Right now it's 200 steps for all.

2022-05-18 08:38 UTC, msuruzhon commented on python/BioSimSpace/Sandpit/Exscientia/FreeEnergy/_relative.py
> +            new_dir = f"{self._work_dir}/lambda_{self._protocol.getLambdaIndex()}"
This changes the default behaviour in the old case of there being a single `fep-lambdas` protocol. I am not really sure what to do about this. Lambda indices are probably better than lambda values but we might have to keep it consistent between engines.

2022-05-18 08:40 UTC, msuruzhon commented on python/BioSimSpace/Sandpit/Exscientia/Protocol/_config.py
> +            protocol_dict["constraints"] = "h-bonds"                            # Rigid bonded hydrogens.
So are `all-bonds` not needed at 4 fs?

2022-05-18 08:43 UTC, msuruzhon commented on python/BioSimSpace/Sandpit/Exscientia/Protocol/_config.py
> +            protocol_dict["refcoord-scaling"] = "com"                               # The actual restraints need to be defined elsewhere.
Even after looking at the documentation, I am not sure what this one does. Is it strictly better for restrained equilibration? What if it is unrestrained?

2022-05-18 08:50 UTC, msuruzhon commented on python/BioSimSpace/Sandpit/Exscientia/Protocol/_free_energy_mixin.py
> +    def setLambda(self, lam):
I find this new API a bit confusing. As far as I understand, currently the `setLambdaValues` does 3 distinct things:

1. Generate the lambda protocol if needed
2. Extensively validate and transform the input as needed
3. Set the lambda value after this

It might make sense to abstract (1) and (2) as private methods, so that `setLambdas` only contains single calls to (1), (2) and the code to actually set the lambda, which is in `setLambda`. Otherwise you risk the chance of calling this with an unvalidated input, which you don't want.

2022-05-18 08:54 UTC, msuruzhon commented on test/Sandpit/Exscientia/Process/test_gromacs.py
> +    assert run_process(system, protocol, extra_options={'verlet-buffer-tolerance': '2e-07'})
Maybe comment on why you are putting these extra options in the test?

2022-05-18 08:58 UTC, msuruzhon requested changes
Thanks @xiki-tempula, this looks largely good to me, but we should address a few comments first.

2022-05-18 09:18 UTC, xiki-tempula commented on test/Sandpit/Exscientia/Process/test_gromacs.py
> +    assert run_process(system, protocol, extra_options={'verlet-buffer-tolerance': '2e-07'})
@msuruzhon If I don't do this, this test will fail. This is a way of trying to remedy it. Though I'm not too sure of why this was not picked up previously.

2022-05-18 09:26 UTC, xiki-tempula commented on python/BioSimSpace/Sandpit/Exscientia/Protocol/_config.py
> +            protocol_dict["refcoord-scaling"] = "com"                               # The actual restraints need to be defined elsewhere.
This is for restrained equilibration and it is about how to alter the reference coordinate when the box volume changes.
My understanding is that say if you have two molecule, one with COM of (1,0,0) and the other with COM of (2,0,0).
If the box shrink by 0.9, `refcoord-scaling = all` will give change the reference coordinates to COM of (0.9,0,0) and COM of (1.8,0,0).
If `refcoord-scaling = com` and the COM of the restraint molecules is the COM of the first molecule, the reference coordinates would change to (0.9,0,0) and (1.9,0,0). So the distance between different restraint molecule stay the same.

I mean if you do `refcoord-scaling = all` with a barostat, Gromacs will just throw a warning so you have no choice.

2022-05-18 09:27 UTC, xiki-tempula commented on python/BioSimSpace/Sandpit/Exscientia/Protocol/_config.py
> +            protocol_dict["constraints"] = "h-bonds"                            # Rigid bonded hydrogens.
`all-bonds` are more stable previously. I don't know why but for 2022, it seems that "h-bonds" are stable enough now.

2022-05-18 11:07 UTC, xiki-tempula commented on python/BioSimSpace/Sandpit/Exscientia/Protocol/_free_energy_mixin.py
> +    def setLambda(self, lam):
@msuruzhon Sorry, what do you mean by "Otherwise you risk the chance of calling this with an unvalidated input, which you don't want."?

2022-05-19 08:37 UTC, msuruzhon commented on python/BioSimSpace/Sandpit/Exscientia/Protocol/_config.py
> +            protocol_dict["constraints"] = "h-bonds"                            # Rigid bonded hydrogens.
That's great then thanks.

2022-05-19 08:38 UTC, msuruzhon commented on python/BioSimSpace/Sandpit/Exscientia/Protocol/_config.py
> +            protocol_dict["refcoord-scaling"] = "com"                               # The actual restraints need to be defined elsewhere.
Ah okay that makes sense thanks.

2022-05-19 08:39 UTC, msuruzhon commented on test/Sandpit/Exscientia/Process/test_gromacs.py
> +    assert run_process(system, protocol, extra_options={'verlet-buffer-tolerance': '2e-07'})
So should we put it in the defaults then? Or only during a vacuum simulation (which I assume this one is?)

2022-05-19 08:39 UTC, xiki-tempula commented on python/BioSimSpace/Sandpit/Exscientia/FreeEnergy/_relative.py
> +            new_dir = f"{self._work_dir}/lambda_{self._protocol.getLambdaIndex()}"
Discussed in https://github.com/michellab/BioSimSpace/issues/315, I guess this is the only option now.

2022-05-19 08:41 UTC, xiki-tempula commented on test/Sandpit/Exscientia/Process/test_gromacs.py
> +    assert run_process(system, protocol, extra_options={'verlet-buffer-tolerance': '2e-07'})
@msuruzhon Ok, I remember now. I think this is due to that I changed from langevin thermostat to V-rescale. I guess Gromacs thinks that this is an issue when you rapidly change the temperature.

2022-05-19 08:46 UTC, msuruzhon commented on python/BioSimSpace/Sandpit/Exscientia/Protocol/_free_energy_mixin.py
> +    def setLambda(self, lam):
I am not sure what I meant actually. But I think what you have now is great thanks.

2022-05-19 08:47 UTC, msuruzhon approved these changes
Thanks @xiki-tempula this looks good.

2022-05-19 08:48 UTC, merged