Address the comments in #363
Exscientia/BioSimSpace pull request #31
Opened 2022-11-11 14:05 UTC by xiki-tempula

@lohedges I have addressed all the comments in https://github.com/michellab/BioSimSpace/pull/363. Do you mind have a check? Thank you.

2022-11-11 14:24 UTC, lohedges commented
Thanks for this, taking a check now.

2022-11-11 14:26 UTC, xiki-tempula commented on python/BioSimSpace/Sandpit/Exscientia/FreeEnergy/_relative.py
> +        files = sorted(_glob(work_dir + "/lambda_*/simfile.dat"))
I have not changed any code here. Just move this out of the if

2022-11-11 14:27 UTC, xiki-tempula commented on python/BioSimSpace/Sandpit/Exscientia/FreeEnergy/_relative.py
> +            overlap = ti
Up to here. No code change, just remove the method not using alchemlyb and deindent the section.

2022-11-11 14:40 UTC, lohedges requested changes
Other than the type check bit, it looks good to me. Thanks for clarifying the spurious diffs.

2022-11-11 14:40 UTC, lohedges commented on python/BioSimSpace/Sandpit/Exscientia/Align/_decouple.py
> +
This won't work because you are checking for an iterable _inside_ a loop that already assumes that the objects are iterable.

Just do a separate type check outside of your loop, e.g.:

```python
if not isinstance(charge, (list, tuple)):
    raise TypeError("...")
if not isinstance(LJ, (list, tuple)):
    raise TypeError("...")
    
# Now your existing loop.
for field, name in zip((charge, LJ), ('charge', 'LJ')):
    if len(field) != 2:
        raise ValueError(f"{name} must only have two values.")

    for value in field:
        if not isinstance(value, bool):
            raise ValueError(f"{value} in {name} must be bool.")
````

2022-11-11 14:58 UTC, lohedges commented on python/BioSimSpace/Sandpit/Exscientia/Align/_decouple.py
> +
Sorry, I missed that you were using `zip` by packing `charge` and `LJ` into tuple, rather than doing `zip(charge, LJ)`, which won't work if they aren't iterable. This is fine :+1:

2022-11-11 17:07 UTC, msuruzhon commented on python/BioSimSpace/Sandpit/Exscientia/FreeEnergy/_relative.py
> +
Too many new lines?

2022-11-11 17:08 UTC, msuruzhon commented on python/BioSimSpace/Sandpit/Exscientia/FreeEnergy/_restraint.py
> +from ..Units.Energy import kcal_per_mol as _kcal_per_mol
Should we sort the imports?

2022-11-11 17:10 UTC, msuruzhon commented on python/BioSimSpace/Sandpit/Exscientia/FreeEnergy/_restraint.py
> +        if engine.replace(" ", "").lower() == 'gromacs':
Isn't `engine.strip().lower()` more standard? Minor point though as this is basically the same in practice (you don't expect somebody to input e.g. `GRO macs`)

2022-11-11 17:11 UTC, msuruzhon approved these changes
LGTM

2022-11-14 09:42 UTC, xiki-tempula commented on python/BioSimSpace/Sandpit/Exscientia/FreeEnergy/_restraint.py
> +from ..Units.Energy import kcal_per_mol as _kcal_per_mol
I think we should probably do this in another PR with black as well.

2022-11-14 09:44 UTC, merged