Add getVolume to Gromacs Process
Exscientia/BioSimSpace pull request #37
Opened 2022-11-22 11:59 UTC by xiki-tempula

This PR adds getVolume to Gromacs Process.

Since the volume is not present in the gromacs text output, this PR switched from reading from gromacs text output to use `gmx energy` to get all the energy terms.

2022-11-22 12:09 UTC, xiki-tempula commented on python/BioSimSpace/Sandpit/Exscientia/Process/_gromacs.py
> +    def _sanitise_energy_term(key):
This one is just copy from the old code. I have not modified this part.

2022-11-22 12:13 UTC, xiki-tempula commented on test/Sandpit/Exscientia/Process/test_gromacs.py
> +    protocol = BSS.Protocol.Equilibration(
A couple black. No code change until the TestGetRecord.

2022-11-22 12:13 UTC, xiki-tempula commented on test/Sandpit/Exscientia/Process/test_gromacs.py
> +
This is new.

2022-11-22 14:11 UTC, msuruzhon commented on .github/workflows/Sandpit_exs.yml
> +          mamba install -c conda-forge -c michellab/label/dev biosimspace python=3.8 ambertools "gromacs!=2022.3" "sire>=2023.0.1" alchemlyb pytest
Shouldn't it always be > 2022.3?

2022-11-22 14:11 UTC, msuruzhon commented on python/BioSimSpace/Sandpit/Exscientia/Process/_gromacs.py
> +        self._engergy_dict = (
Typo

2022-11-22 14:13 UTC, msuruzhon commented on python/BioSimSpace/Sandpit/Exscientia/Process/_gromacs.py
> +    def _initialise_engergy_dict(self):
Typo

2022-11-22 14:17 UTC, msuruzhon commented on test/Sandpit/Exscientia/Process/test_gromacs.py
> +        ],
Nice

2022-11-22 14:23 UTC, xiki-tempula commented on .github/workflows/Sandpit_exs.yml
> +          mamba install -c conda-forge -c michellab/label/dev biosimspace python=3.8 ambertools "gromacs!=2022.3" "sire>=2023.0.1" alchemlyb pytest
The MacOS version of 2022.3 only has double precision one, which will break the BSS. So I set this up to exclude this specific version.
I suspect Sire could only co-exist with certain conda Gromacs version.

2022-11-28 12:35 UTC, lohedges commented
Thanks for this, it is a big improvement over parsing the log file. I'll try to take a proper look over the next few days.

2022-11-30 09:39 UTC, lohedges requested changes
Thanks, this is great. Other than my comments, I was just wondering how you wanted to handle interactive use. Up till now we've returned `None` when specific records are unavailable since the user might be working interactively in a notebook where the simulation might not have reached a checkpoint. I have been thinking about changing this so that an exception is always raised if the process has finished. Perhaps this should also happen when it is still running, but with a different message to inform the user that data might not be ready, e.g. try again later.

Cheers.

2022-11-30 09:39 UTC, lohedges commented on python/BioSimSpace/Sandpit/Exscientia/Process/_gromacs.py
> +        )
Can you use `shell=False`. Using `shell=True` is problematic on some operating systems and can be a security risk if the user can modify the command string. For example, here someone could update the variable `self._exe` to do something rather nasty.

Using `shell=False` is a little more complicated since you need to pass things as a list. To help, we have [command_split](https://github.com/michellab/BioSimSpace/blob/devel/python/BioSimSpace/_Utils/_command_split.py) utility function that works across all operating systems that we support. (The usual `shlex.split` doesn't work correctly on Windows.) It also a bit more complicated if you want to use a pipe, since you need to chain two subprocesses. An example showing how to do this can be found [here](https://github.com/michellab/BioSimSpace/blob/4a2b01d83eba965364d97897f63f6102057b71ea/python/BioSimSpace/Process/_gromacs.py#L2577-L2586).

2022-11-30 09:39 UTC, lohedges commented on python/BioSimSpace/Sandpit/Exscientia/Process/_gromacs.py
> +            self._energy_dict[self._sanitise_energy_term(key)] = []
What happens if the `gmx energy` command fails, or if the output is empty, or corrupted in some way? Is this all captured by the checks at the end of the `_parse_energy_term` function, i.e. line 2103.

2022-11-30 09:39 UTC, lohedges commented on python/BioSimSpace/Sandpit/Exscientia/Process/_gromacs.py
> +                    units.append(_Units.Length.nanometer / _Units.Time.picosecond)
We had decided to report state information in consistent internal units across all engines, rather than returning the unit used by the engine. This is why the documentation was misleading, i.e. we always used `._to_default_unit()` on return. I'm happy for this to be left as is, since I can easily update when it gets pulled out of the sandpit. (It is also trivial to convert after the fact anyway.)

2022-11-30 09:39 UTC, lohedges commented on python/BioSimSpace/Sandpit/Exscientia/Process/_gromacs.py
> +            out, err = proc.communicate()
Use `shell=False` here too.

2022-11-30 09:39 UTC, lohedges commented on python/BioSimSpace/Sandpit/Exscientia/Process/_process.py
> +            and not system._sire_object.search("property velocity")
For checking velocities you can also just check the first molecule of the system, e.g. `system[0]._sire_object.hasProperty("velocity")`, which will avoid searching the whole system. We also allow the user to rename properties, so you need to use the _mapped_ name when checking, e.g.:

```python
velocity_prop = self._property_map.get("velocity", "velocity")
if not system[0]._sire_object.hasProperty(velocity_prop):
    ...
```

2022-12-02 16:14 UTC, xiki-tempula commented on python/BioSimSpace/Sandpit/Exscientia/Process/_process.py
> +            and not system._sire_object.search("property velocity")
Thanks for the suggestion. I wonder what is the self in `self._property_map`?

2023-01-31 15:38 UTC, msuruzhon commented on python/BioSimSpace/Sandpit/Exscientia/Process/_gromacs.py
>          # Initialise the stdout dictionary and title header.
`Initialise the energy dictionary`?

2023-01-31 15:40 UTC, msuruzhon commented on python/BioSimSpace/Sandpit/Exscientia/Process/_gromacs.py
> +        # TODO: the constrained RMSD is a relative quantity and is unitless.
Is this consistent with the previous implementation?

2023-01-31 15:40 UTC, msuruzhon commented on python/BioSimSpace/Sandpit/Exscientia/Process/_gromacs.py
> +        return self.getRecord("VOLUME", time_series, _Units.Volume.angstrom3, block)
Doesn't GROMACS use `nm`?

2023-01-31 15:42 UTC, msuruzhon commented on python/BioSimSpace/Sandpit/Exscientia/Process/_gromacs.py
> +        key = key.replace(")", "")
I think this will be easier with regex but that's also fine.

2023-01-31 15:43 UTC, msuruzhon commented on test/Sandpit/Exscientia/Process/test_gromacs.py
> +from BioSimSpace.Sandpit.Exscientia.Units.Volume import nanometer3
Imports are not sorted.

2023-01-31 15:44 UTC, msuruzhon commented on test/Sandpit/Exscientia/Process/test_gromacs.py
> +        ],
I was about to say "Nice" then I saw that I already said that. Anyway, nice.

2023-01-31 15:52 UTC, xiki-tempula commented on python/BioSimSpace/Sandpit/Exscientia/Process/_gromacs.py
> +        # TODO: the constrained RMSD is a relative quantity and is unitless.
Yes

2023-01-31 15:54 UTC, xiki-tempula commented on python/BioSimSpace/Sandpit/Exscientia/Process/_gromacs.py
> +        return self.getRecord("VOLUME", time_series, _Units.Volume.angstrom3, block)
This is a get method, which means get the result in A^3

2023-02-01 11:10 UTC, merged